### ISSUE TITLE
Please provide an example of subscribing to unique computer or scale

### ISSUE THREAD

**Issue by rcojoe** [PrintNode/PrintNode-JS#7]
Could you provide an example of subscribing to a scale or computer?  The example given subscribes to all computers and scales, so I tried subscribing to topic computer/1234, where 1234 is my computer id  but it failed.

**Comment by prvnbist** [comment]
Any solution yet?

**Comment by rcojoe** [comment]
I can only share my previous experience.  The quick answer is using a generic MQTT client to figure out exactly what to subscribe to.  The bigger issue that you will discover once you have your single scale subscription figured out and you start to scale your deployment, the next hurdle is there can only be 6 or 8 scales hooked up to each printnode account. This shouldn't be considered a limit though because it helps keep the client from loading up with needless traffic.  You can manage multiple locations by signing up for an integrator account, which I did.  I was able to create as many child accounts (one for each scale) as I needed.  There is a burst of scale traffic when it is being updated, so even with multiple scales on a single account, I was able to filter down to just the scale in question without any performance issues.
